# Generated by Django 3.1.7 on 2021-02-26 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Type of animal')),
                ('is_predator', models.BooleanField(default=False, verbose_name='Is it a predator?')),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name of animal')),
                ('code', models.PositiveIntegerField(verbose_name='Code of animal')),
                ('latitude', models.FloatField(verbose_name='Latitude of animal')),
                ('longitude', models.FloatField(verbose_name='Longitude of animal')),
                ('animal_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.animaltype', verbose_name='Type of animal')),
            ],
        ),
    ]
