# Generated by Django 3.1.7 on 2021-02-26 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_auto_20210226_0830'),
    ]

    operations = [
        migrations.AddField(
            model_name='animaltype',
            name='is_caught',
            field=models.BooleanField(default=False, verbose_name='Is caught?'),
        ),
    ]
