# Generated by Django 3.1.7 on 2021-02-26 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0003_animaltype_is_caught'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animaltype',
            name='is_caught',
        ),
        migrations.AddField(
            model_name='animal',
            name='is_caught',
            field=models.BooleanField(default=False, verbose_name='Is caught?'),
        ),
    ]
